name: Code Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server-tests:
    name: Server Tests (Flask)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install backend dependencies
        working-directory: server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backend tests
        working-directory: server
        env:
          # Using SQLite for tests; modify DATABASE_URL if needed.
          DATABASE_URL: "sqlite:///:memory:"
          FLASK_ENV: "testing"
        run: pytest

  client-tests:
    name: Client Tests (React)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install frontend dependencies
        working-directory: client
        run: npm install
      - name: Run frontend tests
        working-directory: client
        run: npm run test --if-present

  extension-tests:
    name: Chrome Extension Tests (Optional)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install extension dependencies
        working-directory: chrome-extension
        run: npm install
      - name: Run extension tests
        working-directory: chrome-extension
        run: npm test --if-present
